# Generated by Django 5.0.2 on 2024-03-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zay', '0004_category_desc_cat_category_image_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='desc_cat',
        ),
    ]
