# Generated by Django 5.0.2 on 2024-03-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zay', '0005_remove_category_desc_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='titre',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
